#!/usr/bin/env bash
set -euo pipefail

# Round-4 targeted relabeling for the last remaining shortage:
#   visual_substrate/diagram
#
# Use after v5 has already solved chart and text_reading. This round only mines
# diagram-like sources, with IconQA as the primary source.

PROJECT_ROOT="${PROJECT_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
RAW_ROOT="${RAW_ROOT:-$PROJECT_ROOT/cl_dataset/coin}"

BASE_TRAIN_JSON="${BASE_TRAIN_JSON:-$PROJECT_ROOT/cl_dataset/coin_factor1_train_v5/train.json}"
POOL_ROOT="${POOL_ROOT:-$PROJECT_ROOT/cl_dataset/coin_factor1_targeted_pool_v6_iconqa}"
TARGET_ROOT="${TARGET_ROOT:-$PROJECT_ROOT/cl_dataset/coin_factor1_targeted_meta_v6_iconqa}"
TARGETED_TRAIN_ROOT="${TARGETED_TRAIN_ROOT:-$PROJECT_ROOT/cl_dataset/coin_factor1_targeted_train_v6_iconqa}"
MERGED_TRAIN_ROOT="${MERGED_TRAIN_ROOT:-$PROJECT_ROOT/cl_dataset/coin_factor1_train_v6}"
SPLIT_ROOT="${SPLIT_ROOT:-$PROJECT_ROOT/cl_dataset/coin_factor1_10k_v6}"

DATASETS_OVERRIDE="${DATASETS_OVERRIDE:-iconqa ai2d scienceqa}"

TARGET_COUNT="${TARGET_COUNT:-13000}"
POOL_MAX_SAMPLES_PER_DATASET="${POOL_MAX_SAMPLES_PER_DATASET:-100000}"
MAX_TOTAL_CANDIDATES="${MAX_TOTAL_CANDIDATES:-30000}"
CANDIDATE_MULTIPLIER="${CANDIDATE_MULTIPLIER:-5.0}"
MIN_SCORE="${MIN_SCORE:-3}"
MIN_CANDIDATES_PER_DEFICIT="${MIN_CANDIDATES_PER_DEFICIT:-5000}"
MAX_CANDIDATES_PER_CATEGORY="${MAX_CANDIDATES_PER_CATEGORY:-30000}"

API_BASE="${API_BASE:-http://127.0.0.1:8001/v1}"
API_KEY="${API_KEY:-EMPTY}"
MODEL="${MODEL:-qwen3.6}"
BATCH_SIZE="${BATCH_SIZE:-1}"
MAX_TOKENS="${MAX_TOKENS:-4096}"
TIMEOUT="${TIMEOUT:-300}"
RETRIES="${RETRIES:-2}"

RUN_SPLIT_CHECK="${RUN_SPLIT_CHECK:-1}"
SELECT_ONLY="${SELECT_ONLY:-0}"
BUILD_POOL="${BUILD_POOL:-1}"
ALLOW_MISSING_DATASETS="${ALLOW_MISSING_DATASETS:-1}"
CHECK_RAW_DATASETS="${CHECK_RAW_DATASETS:-1}"

export RAW_ROOT BASE_TRAIN_JSON POOL_ROOT TARGET_ROOT TARGETED_TRAIN_ROOT MERGED_TRAIN_ROOT SPLIT_ROOT
export DATASETS_OVERRIDE TARGET_COUNT POOL_MAX_SAMPLES_PER_DATASET MAX_TOTAL_CANDIDATES CANDIDATE_MULTIPLIER
export MIN_SCORE MIN_CANDIDATES_PER_DEFICIT MAX_CANDIDATES_PER_CATEGORY
export API_BASE API_KEY MODEL BATCH_SIZE MAX_TOKENS TIMEOUT RETRIES RUN_SPLIT_CHECK SELECT_ONLY BUILD_POOL
export ALLOW_MISSING_DATASETS CHECK_RAW_DATASETS

bash "$PROJECT_ROOT/scripts/run_factor1_targeted_relabel_round3_add_sources.sh"
